### ISSUE TITLE
Bitmap darawables / Icons missing

### ISSUE THREAD

**Issue by muragewanjohi** [kevgichohi/cleanup#59]
Image resources have only been set for hdpi. We need the same images for ldpi, mdpi, xhdpi, xxhdpi. 

**NB: Only png images**
- 36x36 (0.75x) for low-density
- 48x48 (1.0x baseline) for medium-density
- 72x72 (1.5x) for high-density
- 96x96 (2.0x) for extra-high-density
- 144x144 (3.0x) for extra-extra-high-density
- 192x192 (4.0x) for extra-extra-extra-high-density 

See [Guidline for details](https://developer.android.com/guide/practices/screens_support.html)

**Comment by kevgichohi** [comment]
[mipmap-hdpi.zip](https://github.com/kevgichohi/cleanup/files/426670/mipmap-hdpi.zip)

Hi Bob please see drawables that require different sizes as mentioned.
