### ISSUE TITLE
Kinetech Ltd, not showing place holders

### ISSUE THREAD

**Issue by muragewanjohi** [kevgichohi/cleanup#8]
Place holders not showing on all categories

**Comment by z-01** [comment]
@kevgichohi the app is searching for the images in the smoke signal server. Are the images in the e-fam server ?

**Comment by kevgichohi** [comment]
All the files were moved to the e-fam server. This maybe the reason why they are not showing

**Comment by kevgichohi** [comment]
They spaces provided should show the place holder designed

**Comment by kevgichohi** [comment]
This is ok. Images in the place holders are showing
